export const REACT_APP_API = process.env.REACT_APP_API
export const REACT_APP_GOOGLE_CLIENT_ID = process.env.REACT_APP_GOOGLE_CLIENT_ID
export const REACT_APP_API_YANDEX_METRICA_ID = process.env.REACT_APP_API_YANDEX_METRICA_ID
